In [1]:
!pip install packaging

Requirement already satisfied: packaging in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (25.0)

[notice] A new release of pip available: 22.3 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
!pip install statsbombpy
!pip install pandas
!pip install networkx

Collecting statsbombpy
  Downloading statsbombpy-1.16.0-py3-none-any.whl (16 kB)
Collecting pandas
  Downloading pandas-2.3.3-cp311-cp311-win_amd64.whl (11.3 MB)
     --------------------------------------- 11.3/11.3 MB 17.2 MB/s eta 0:00:00
Collecting requests
  Downloading requests-2.32.5-py3-none-any.whl (64 kB)
     ---------------------------------------- 64.7/64.7 kB ? eta 0:00:00
Collecting requests-cache
  Downloading requests_cache-1.2.1-py3-none-any.whl (61 kB)
     ---------------------------------------- 61.4/61.4 kB ? eta 0:00:00
Collecting inflect
  Downloading inflect-7.5.0-py3-none-any.whl (35 kB)
Collecting joblib
  Downloading joblib-1.5.2-py3-none-any.whl (308 kB)
     ------------------------------------- 308.4/308.4 kB 19.9 MB/s eta 0:00:00
Collecting more_itertools>=8.5.0
  Downloading more_itertools-10.8.0-py3-none-any.whl (69 kB)
     ---------------------------------------- 69.7/69.7 kB ? eta 0:00:00
Collecting typeguard>=4.0.1
  Downloading typeguard-4.4.4-py3-none-any.whl (34 kB)
Collecting numpy>=1.23.2
  Downloading numpy-2.3.5-cp311-cp311-win_amd64.whl (13.1 MB)
     --------------------------------------- 13.1/13.1 MB 18.7 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jonat\appdata\roaming\python\python311\site-packages (from pandas->statsbombpy) (2.9.0.post0)
Collecting pytz>=2020.1
  Downloading pytz-2025.2-py2.py3-none-any.whl (509 kB)
     ------------------------------------- 509.2/509.2 kB 16.1 MB/s eta 0:00:00
Collecting tzdata>=2022.7
  Downloading tzdata-2025.2-py2.py3-none-any.whl (347 kB)
     ------------------------------------- 347.8/347.8 kB 21.1 MB/s eta 0:00:00
Collecting charset_normalizer<4,>=2
  Downloading charset_normalizer-3.4.4-cp311-cp311-win_amd64.whl (106 kB)
     -------------------------------------- 107.0/107.0 kB 6.0 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.11-py3-none-any.whl (71 kB)
     ---------------------------------------- 71.0/71.0 kB 3.8 MB/s eta 0:00:00
Collecting urllib3<3,>=1.21.1
  Downloading urllib3-2.5.0-py3-none-any.whl (129 kB)
     ---------------------------------------- 129.8/129.8 kB ? eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2025.11.12-py3-none-any.whl (159 kB)
     -------------------------------------- 159.4/159.4 kB 9.9 MB/s eta 0:00:00
Collecting attrs>=21.2
  Downloading attrs-25.4.0-py3-none-any.whl (67 kB)
     ---------------------------------------- 67.6/67.6 kB ? eta 0:00:00
Collecting cattrs>=22.2
  Downloading cattrs-25.3.0-py3-none-any.whl (70 kB)
     ---------------------------------------- 70.7/70.7 kB ? eta 0:00:00
Requirement already satisfied: platformdirs>=2.5 in c:\users\jonat\appdata\roaming\python\python311\site-packages (from requests-cache->statsbombpy) (4.5.0)
Collecting url-normalize>=1.4
  Downloading url_normalize-2.2.1-py3-none-any.whl (14 kB)
Requirement already satisfied: typing-extensions>=4.14.0 in c:\users\jonat\appdata\roaming\python\python311\site-packages (from cattrs>=22.2->requests-cache->statsbombpy) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\users\jonat\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas->statsbombpy) (1.17.0)
Installing collected packages: pytz, urllib3, tzdata, typeguard, numpy, more_itertools, joblib, idna, charset_normalizer, certifi, attrs, url-normalize, requests, pandas, inflect, cattrs, requests-cache, statsbombpy
Successfully installed attrs-25.4.0 cattrs-25.3.0 certifi-2025.11.12 charset_normalizer-3.4.4 idna-3.11 inflect-7.5.0 joblib-1.5.2 more_itertools-10.8.0 numpy-2.3.5 pandas-2.3.3 pytz-2025.2 requests-2.32.5 requests-cache-1.2.1 statsbombpy-1.16.0 typeguard-4.4.4 tzdata-2025.2 url-normalize-2.2.1 urllib3-2.5.0

[notice] A new release of pip available: 22.3 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.23.2 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jonat\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\jonat\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip available: 22.3 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting networkx
  Downloading networkx-3.6-py3-none-any.whl (2.1 MB)
     ---------------------------------------- 2.1/2.1 MB 8.2 MB/s eta 0:00:00
Installing collected packages: networkx
Successfully installed networkx-3.6

[notice] A new release of pip available: 22.3 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import statsbombpy
from statsbombpy import sb
import pandas as pd

In [6]:
matches = sb.matches(competition_id=2, season_id=27)
matches.head()

c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,match_id,match_date,kick_off,competition,season,home_team,away_team,home_score,away_score,match_status,...,last_updated_360,match_week,competition_stage,stadium,referee,home_managers,away_managers,data_version,shot_fidelity_version,xy_fidelity_version
0,3754058,2016-01-02,16:00:00.000,England - Premier League,2015/2016,Leicester City,AFC Bournemouth,0,0,available,...,2021-06-12T16:17:31.694,20,Regular Season,King Power Stadium,Andre Marriner,Claudio Ranieri,Eddie Howe,1.1.0,2,2
1,3754245,2015-10-17,16:00:00.000,England - Premier League,2015/2016,West Bromwich Albion,Sunderland,1,0,available,...,2021-06-13T16:17:31.694,9,Regular Season,The Hawthorns,Martin Atkinson,Tony Pulis,Sam Allardyce,1.1.0,2,2
2,3754136,2015-12-19,18:30:00.000,England - Premier League,2015/2016,Newcastle United,Aston Villa,1,1,available,...,2021-06-13T16:17:31.694,17,Regular Season,St. James'' Park,Martin Atkinson,Steve McClaren,Rémi Garde,1.1.0,2,2
3,3754037,2016-04-30,16:00:00.000,England - Premier League,2015/2016,Everton,AFC Bournemouth,2,1,available,...,2021-06-12T16:17:31.694,36,Regular Season,Goodison Park,Neil Swarbrick,Roberto Martínez Montoliú,Eddie Howe,1.1.0,2,2
4,3754039,2016-02-13,16:00:00.000,England - Premier League,2015/2016,Crystal Palace,Watford,1,2,available,...,2021-06-12T16:17:31.694,26,Regular Season,Selhurst Park,Robert Madley,Alan Pardew,Enrique Sánchez Flores,1.1.0,2,2

In [7]:
# Get the first match ID
match_id = matches.iloc[0]['match_id']

# Load event data
events = sb.events(match_id=match_id)
events.head()

c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

,ball_receipt_outcome,ball_recovery_recovery_failure,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_right_foot,counterpress,dribble_nutmeg,...,substitution_outcome,substitution_outcome_id,substitution_replacement,substitution_replacement_id,tactics,team,team_id,timestamp,type,under_pressure
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 442, 'lineup': [{'player': {'id'...",Leicester City,22,00:00:00.000,Starting XI,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,"{'formation': 4141, 'lineup': [{'player': {'id...",AFC Bournemouth,28,00:00:00.000,Starting XI,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,AFC Bournemouth,28,00:00:00.000,Half Start,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,Leicester City,22,00:00:00.000,Half Start,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,AFC Bournemouth,28,00:00:00.000,Half Start,NaN

In [8]:
all_events = []
for match_id in matches['match_id']:
    events = sb.events(match_id=match_id)
    events['match_id'] = match_id
    all_events.append(events)

# Combine into one big DataFrame
pl_2015_2016_events = pd.concat(all_events, ignore_index=True)

c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [9]:
pl_2015_2016_events.head()

,ball_receipt_outcome,ball_recovery_recovery_failure,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_right_foot,counterpress,dribble_nutmeg,...,block_save_block,shot_deflected,player_off_permanent,goalkeeper_success_in_play,shot_follows_dribble,goalkeeper_lost_out,half_start_late_video_start,goalkeeper_lost_in_play,goalkeeper_penalty_saved_to_post,goalkeeper_saved_to_post
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
leicester_matches = matches[(matches['home_team'] == "Leicester City") | 
                            (matches['away_team'] == "Leicester City")]

In [11]:
events_list = []
for match_id in leicester_matches['match_id']:
    df = sb.events(match_id=match_id)
    events_list.append(df)

events = pd.concat(events_list, ignore_index=True)

c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(
c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\statsbombpy\api_client.py:21: NoAuthWarning: credentials were not supplied. open data access only
  warnings.warn(

In [12]:
import numpy as np

In [13]:
# copy to avoid SettingWithCopyWarning and extract X coordinate from location
lec_events = events[events['team'] == 'Leicester City'].copy()
lec_events['x'] = lec_events['location'].apply(
    lambda loc: loc[0] if isinstance(loc, (list, tuple)) and len(loc) >= 1 else np.nan
)

In [14]:
# filter to attacking third (x between 80 and 120)
att_third = lec_events[(lec_events['x'] >= 80) & (lec_events['x'] <= 120)].copy()

In [15]:
# mark unsuccessful dribbles where type == 'Dribble' and dribble_outcome == 'Incomplete'
att_third['unsuccessful_dribble'] = (
    (att_third['type'] == 'Dribble') & (att_third['dribble_outcome'] == 'Incomplete')
).astype(int)

# aggregate per player using only attacking-third events
possession_ending_actions = att_third.groupby('player').agg(
    shots=('type', lambda x: (x == 'Shot').sum()),
    dispossessed=('type', lambda x: (x == 'Dispossessed').sum()),
    miscontrols=('type', lambda x: (x == 'Miscontrol').sum()),
    incomplete_passes=('pass_outcome', lambda x: x.notna().sum()),
    unsuccessful_dribbles=('unsuccessful_dribble', 'sum')
).reset_index()

In [16]:
cols = ['shots','dispossessed','miscontrols','incomplete_passes','unsuccessful_dribbles']
possession_ending_actions[cols] = possession_ending_actions[cols].fillna(0).astype(int)
possession_ending_actions['possession_ending_actions'] = possession_ending_actions[cols].sum(axis=1)

In [17]:
possession_ending_actions

,player,shots,dispossessed,miscontrols,incomplete_passes,unsuccessful_dribbles,possession_ending_actions
0,Andrej Kramarić,1,0,1,2,0,4
1,Andrew Philip King,19,3,2,31,3,58
2,Christian Fuchs,19,3,7,188,1,218
3,Daniel Amartey,1,2,0,3,1,7
4,Danny Drinkwater,42,16,7,94,3,162
5,Danny Simpson,7,4,3,89,6,109
6,Demarai Gray,5,4,3,14,2,28
7,Gökhan İnler,2,0,0,6,1,9
8,Jamie Vardy,118,30,58,154,30,390
9,Jeffrey Schlupp,25,23,20,56,15,139
10,Joe Dodoo,0,1,1,0,0,2
11,José Leonardo Ulloa,33,19,26,48,5,131
12,Kasper Schmeichel,0,0,0,0,0,0
13,Marc Albrighton,42,23,20,299,27,411
14,Marcin Ryszard Wasilewski,1,0,0,0,0,1
15,N''Golo Kanté,21,20,12,72,5,130
16,Nathan Dyer,5,4,7,12,2,30
17,Ritchie De Laet,2,2,2,25,7,38
18,Riyad Mahrez,87,56,49,210,63,465
19,Robert Huth,30,0,5,7,0,42
20,Shinji Okazaki,44,32,47,57,12,192
21,Wes Morgan,21,2,5,14,0,42
22,Yohan Benalouane,0,1,0,1,0,2

In [18]:
# find possession_ending actions for Leceister City as a team
shots = (att_third['type'] == 'Shot').sum()
dispossessed = (att_third['type'] == 'Dispossessed').sum()
miscontrols = (att_third['type'] == 'Miscontrol').sum()
incomplete_passes = att_third['pass_outcome'].notna().sum()
unsuccessful_dribbles = att_third['unsuccessful_dribble'].sum()

In [19]:
team_totals = pd.DataFrame([{
    'team': 'Leicester City',
    'shots': shots,
    'dispossessed': dispossessed,
    'miscontrols': miscontrols,
    'incomplete_passes': incomplete_passes,
    'unsuccessful_dribbles': unsuccessful_dribbles,
    'possession ending actions': (shots + dispossessed + miscontrols + incomplete_passes + unsuccessful_dribbles)
}])
team_totals

,team,shots,dispossessed,miscontrols,incomplete_passes,unsuccessful_dribbles,possession ending actions
0,Leicester City,525,245,275,1382,183,2610

# Change to per90 numbers
# Add chances created per 90 - find G/Aper90 as well, so we can compare usage rate to these numbers - look at wyscout

In [20]:
duel_values = lec_events['duel_outcome'].value_counts(dropna=False)
duel_values

duel_outcome
NaN                55700
Success In Play      292
Won                  210
Lost Out             172
Lost In Play         167
Success Out           26
Name: count, dtype: int64

In [21]:
type_values = lec_events['type'].value_counts(dropna=False)
type_values

# find values for when 'type' equals Dribble
dribble_values = lec_events[lec_events['type'] == 'Dribble']
dribble_values['dribble_outcome'].value_counts(dropna=False)

dribble_outcome
Complete      429
Incomplete    296
Name: count, dtype: int64

In [22]:
# create usage rate by dividing player possession ending actions by team total, and display usage rate with two decimal places
possession_ending_actions['Usage Rate'] = ((possession_ending_actions['possession_ending_actions'] / team_totals['possession ending actions'].values[0]) * 100).round(2)

In [23]:
possession_ending_actions

,player,shots,dispossessed,miscontrols,incomplete_passes,unsuccessful_dribbles,possession_ending_actions,Usage Rate
0,Andrej Kramarić,1,0,1,2,0,4,0.15
1,Andrew Philip King,19,3,2,31,3,58,2.22
2,Christian Fuchs,19,3,7,188,1,218,8.35
3,Daniel Amartey,1,2,0,3,1,7,0.27
4,Danny Drinkwater,42,16,7,94,3,162,6.21
5,Danny Simpson,7,4,3,89,6,109,4.18
6,Demarai Gray,5,4,3,14,2,28,1.07
7,Gökhan İnler,2,0,0,6,1,9,0.34
8,Jamie Vardy,118,30,58,154,30,390,14.94
9,Jeffrey Schlupp,25,23,20,56,15,139,5.33
10,Joe Dodoo,0,1,1,0,0,2,0.08
11,José Leonardo Ulloa,33,19,26,48,5,131,5.02
12,Kasper Schmeichel,0,0,0,0,0,0,0.00
13,Marc Albrighton,42,23,20,299,27,411,15.75
14,Marcin Ryszard Wasilewski,1,0,0,0,0,1,0.04
15,N''Golo Kanté,21,20,12,72,5,130,4.98
16,Nathan Dyer,5,4,7,12,2,30,1.15
17,Ritchie De Laet,2,2,2,25,7,38,1.46
18,Riyad Mahrez,87,56,49,210,63,465,17.82
19,Robert Huth,30,0,5,7,0,42,1.61
20,Shinji Okazaki,44,32,47,57,12,192,7.36
21,Wes Morgan,21,2,5,14,0,42,1.61
22,Yohan Benalouane,0,1,0,1,0,2,0.08

In [ ]:
# !pip install statsbombpy
# !pip install pandas
# !pip install networkx
# !pip install soccerdata
# !pip install setuptools
# !pip install pyarrow
# !pip install polars

Requirement already satisfied: statsbombpy in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (1.16.0)
Requirement already satisfied: pandas in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from statsbombpy) (2.3.3)
Requirement already satisfied: requests in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from statsbombpy) (2.32.5)
Requirement already satisfied: requests-cache in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from statsbombpy) (1.2.1)
Requirement already satisfied: inflect in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from statsbombpy) (7.5.0)
Requirement already satisfied: joblib in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from statsbombpy) (1.5.2)
Requirement already satisfied: more_itertools>=8.5.0 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from inflect->statsbombpy) (10.8.0)
Requirement already satisfied: typeguard>=4.0.1 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from inflect->statsbombpy) (4.4.4)
Requirement already satisfied: numpy>=1.23.2 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from pandas->statsbombpy) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jonat\appdata\roaming\python\python311\site-packages (from pandas->statsbombpy) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from pandas->statsbombpy) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from pandas->statsbombpy) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from requests->statsbombpy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from requests->statsbombpy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from requests->statsbombpy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from requests->statsbombpy) (2025.11.12)
Requirement already satisfied: attrs>=21.2 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from requests-cache->statsbombpy) (25.4.0)
Requirement already satisfied: cattrs>=22.2 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from requests-cache->statsbombpy) (25.3.0)
Requirement already satisfied: platformdirs>=2.5 in c:\users\jonat\appdata\roaming\python\python311\site-packages (from requests-cache->statsbombpy) (4.5.0)
Requirement already satisfied: url-normalize>=1.4 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from requests-cache->statsbombpy) (2.2.1)
Requirement already satisfied: typing-extensions>=4.14.0 in c:\users\jonat\appdata\roaming\python\python311\site-packages (from cattrs>=22.2->requests-cache->statsbombpy) (4.15.0)
Requirement already satisfied: six>=1.5 in c:\users\jonat\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas->statsbombpy) (1.17.0)

[notice] A new release of pip available: 22.3 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: pandas in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.23.2 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jonat\appdata\roaming\python\python311\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\jonat\appdata\roaming\python\python311\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip available: 22.3 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: networkx in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (3.6)

[notice] A new release of pip available: 22.3 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting soccerdata
  Downloading soccerdata-1.8.7-py3-none-any.whl (58 kB)
     ---------------------------------------- 58.0/58.0 kB 1.5 MB/s eta 0:00:00
Collecting PySocks<2.0.0,>=1.7.1
  Downloading PySocks-1.7.1-py3-none-any.whl (16 kB)
Collecting Unidecode<2.0.0,>=1.2.0
  Downloading Unidecode-1.4.0-py3-none-any.whl (235 kB)
     -------------------------------------- 235.8/235.8 kB 3.6 MB/s eta 0:00:00
Collecting cloudscraper<2.0.0,>=1.2.71
  Downloading cloudscraper-1.2.71-py2.py3-none-any.whl (99 kB)
     ---------------------------------------- 99.7/99.7 kB 6.0 MB/s eta 0:00:00
Collecting html5lib<2.0,>=1.1
  Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
     -------------------------------------- 112.2/112.2 kB 6.4 MB/s eta 0:00:00
Collecting lxml<5.0.0,>=4.9.3
  Downloading lxml-4.9.4-cp311-cp311-win_amd64.whl (3.8 MB)
     ---------------------------------------- 3.8/3.8 MB 13.4 MB/s eta 0:00:00
Collecting packaging<25.0,>=24.1
  Downloading packaging-24.2-py3-none-any.whl (65 kB)
     ---------------------------------------- 65.5/65.5 kB 3.5 MB/s eta 0:00:00
Requirement already satisfied: pandas!=2.1.0,<3.0.0,>=2.0.0 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from soccerdata) (2.3.3)
Requirement already satisfied: requests<3.0,>=2.23 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from soccerdata) (2.32.5)
Collecting rich<14.0.0,>=13.0.0
  Downloading rich-13.9.4-py3-none-any.whl (242 kB)
     ---------------------------------------- 242.4/242.4 kB ? eta 0:00:00
Collecting undetected-chromedriver<4.0.0,>=3.5.0
  Downloading undetected-chromedriver-3.5.5.tar.gz (65 kB)
     ---------------------------------------- 65.4/65.4 kB 3.4 MB/s eta 0:00:00
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Collecting unicode<3.0,>=2.7
  Downloading unicode-2.9-py2.py3-none-any.whl (14 kB)
Collecting pyparsing>=2.4.7
  Downloading pyparsing-3.2.5-py3-none-any.whl (113 kB)
     ---------------------------------------- 113.9/113.9 kB ? eta 0:00:00
Collecting requests-toolbelt>=0.9.1
  Downloading requests_toolbelt-1.0.0-py2.py3-none-any.whl (54 kB)
     ---------------------------------------- 54.5/54.5 kB ? eta 0:00:00
Requirement already satisfied: six>=1.9 in c:\users\jonat\appdata\roaming\python\python311\site-packages (from html5lib<2.0,>=1.1->soccerdata) (1.17.0)
Collecting webencodings
  Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
Requirement already satisfied: numpy>=1.23.2 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from pandas!=2.1.0,<3.0.0,>=2.0.0->soccerdata) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jonat\appdata\roaming\python\python311\site-packages (from pandas!=2.1.0,<3.0.0,>=2.0.0->soccerdata) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from pandas!=2.1.0,<3.0.0,>=2.0.0->soccerdata) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from pandas!=2.1.0,<3.0.0,>=2.0.0->soccerdata) (2025.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0,>=2.23->soccerdata) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0,>=2.23->soccerdata) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0,>=2.23->soccerdata) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from requests<3.0,>=2.23->soccerdata) (2025.11.12)
Collecting markdown-it-py>=2.2.0
  Downloading markdown_it_py-4.0.0-py3-none-any.whl (87 kB)
     ---------------------------------------- 87.3/87.3 kB ? eta 0:00:00
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\jonat\appdata\roaming\python\python311\site-packages (from rich<14.0.0,>=13.0.0->soccerdata) (2.19.2)
Collecting selenium>=4.9.0
  Downloading selenium-4.38.0-py3-none-any.whl (9.7 MB)
     ---------------------------------------- 9.7/9.7 MB 21.4 MB/s eta 0:00:00
Collecting websockets
  Downloading websockets-15.0.1-cp311-cp311-win_amd64.whl (176 kB)
     ---------------------------------------- 176.8/176.8 kB ? eta 0:00:00
Collecting mdurl~=0.1
  Downloading mdurl-0.1.2-py3-none-any.whl (10.0 kB)
Collecting trio<1.0,>=0.31.0
  Downloading trio-0.32.0-py3-none-any.whl (512 kB)
     ------------------------------------- 512.0/512.0 kB 31.4 MB/s eta 0:00:00
Collecting trio-websocket<1.0,>=0.12.2
  Downloading trio_websocket-0.12.2-py3-none-any.whl (21 kB)
Requirement already satisfied: typing_extensions<5.0,>=4.15.0 in c:\users\jonat\appdata\roaming\python\python311\site-packages (from selenium>=4.9.0->undetected-chromedriver<4.0.0,>=3.5.0->soccerdata) (4.15.0)
Collecting websocket-client<2.0,>=1.8.0
  Downloading websocket_client-1.9.0-py3-none-any.whl (82 kB)
     ---------------------------------------- 82.6/82.6 kB ? eta 0:00:00
Requirement already satisfied: attrs>=23.2.0 in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (from trio<1.0,>=0.31.0->selenium>=4.9.0->undetected-chromedriver<4.0.0,>=3.5.0->soccerdata) (25.4.0)
Collecting sortedcontainers
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Collecting outcome
  Downloading outcome-1.3.0.post0-py2.py3-none-any.whl (10 kB)
Collecting sniffio>=1.3.0
  Downloading sniffio-1.3.1-py3-none-any.whl (10 kB)
Collecting cffi>=1.14
  Downloading cffi-2.0.0-cp311-cp311-win_amd64.whl (182 kB)
     ------------------------------------- 182.8/182.8 kB 10.8 MB/s eta 0:00:00
Collecting wsproto>=0.14
  Downloading wsproto-1.3.2-py3-none-any.whl (24 kB)
Collecting pycparser
  Downloading pycparser-2.23-py3-none-any.whl (118 kB)
     ---------------------------------------- 118.1/118.1 kB ? eta 0:00:00
Collecting h11<1,>=0.16.0
  Downloading h11-0.16.0-py3-none-any.whl (37 kB)
Installing collected packages: webencodings, unicode, sortedcontainers, websockets, websocket-client, Unidecode, sniffio, PySocks, pyparsing, pycparser, packaging, outcome, mdurl, lxml, html5lib, h11, wsproto, requests-toolbelt, markdown-it-py, cffi, trio, rich, cloudscraper, trio-websocket, selenium, undetected-chromedriver, soccerdata
  Attempting uninstall: packaging
    Found existing installation: packaging 25.0
    Uninstalling packaging-25.0:
      Successfully uninstalled packaging-25.0
  Running setup.py install for undetected-chromedriver: started
  Running setup.py install for undetected-chromedriver: finished with status 'done'
Successfully installed PySocks-1.7.1 Unidecode-1.4.0 cffi-2.0.0 cloudscraper-1.2.71 h11-0.16.0 html5lib-1.1 lxml-4.9.4 markdown-it-py-4.0.0 mdurl-0.1.2 outcome-1.3.0.post0 packaging-24.2 pycparser-2.23 pyparsing-3.2.5 requests-toolbelt-1.0.0 rich-13.9.4 selenium-4.38.0 sniffio-1.3.1 soccerdata-1.8.7 sortedcontainers-2.4.0 trio-0.32.0 trio-websocket-0.12.2 undetected-chromedriver-3.5.5 unicode-2.9 webencodings-0.5.1 websocket-client-1.9.0 websockets-15.0.1 wsproto-1.3.2

  DEPRECATION: undetected-chromedriver is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

[notice] A new release of pip available: 22.3 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: setuptools in c:\users\jonat\appdata\local\programs\python\python311\lib\site-packages (65.5.0)

[notice] A new release of pip available: 22.3 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting pyarrow
  Downloading pyarrow-22.0.0-cp311-cp311-win_amd64.whl (28.1 MB)
     --------------------------------------- 28.1/28.1 MB 29.8 MB/s eta 0:00:00
Installing collected packages: pyarrow
Successfully installed pyarrow-22.0.0

[notice] A new release of pip available: 22.3 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting polars
  Downloading polars-1.35.2-py3-none-any.whl (783 kB)
     -------------------------------------- 783.6/783.6 kB 8.2 MB/s eta 0:00:00
Collecting polars-runtime-32==1.35.2
  Downloading polars_runtime_32-1.35.2-cp39-abi3-win_amd64.whl (41.3 MB)
     --------------------------------------- 41.3/41.3 MB 19.2 MB/s eta 0:00:00
Installing collected packages: polars-runtime-32, polars
Successfully installed polars-1.35.2 polars-runtime-32-1.35.2

[notice] A new release of pip available: 22.3 -> 25.3
[notice] To update, run: python.exe -m pip install --upgrade pip

In [25]:
import sys, subprocess

print("Python executable:", sys.executable)
subprocess.run([sys.executable, "-m", "pip", "show", "soccerdata"])

Python executable: c:\Users\jonat\AppData\Local\Programs\Python\Python311\python.exe

CompletedProcess(args=['c:\\Users\\jonat\\AppData\\Local\\Programs\\Python\\Python311\\python.exe', '-m', 'pip', 'show', 'soccerdata'], returncode=0)

In [27]:
import soccerdata as sd

[11/26/25 21:05:33] INFO     No custom team name replacements found. You can configure these in       ]8;id=651377;file://c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\soccerdata\_config.py\_config.py]8;;\:]8;id=440144;file://c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\soccerdata\_config.py#91\91]8;;\
                             C:\Users\jonat\soccerdata\config\teamname_replacements.json.

                    INFO     No custom league dict found. You can configure additional leagues in    ]8;id=823482;file://c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\soccerdata\_config.py\_config.py]8;;\:]8;id=364199;file://c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\soccerdata\_config.py#197\197]8;;\
                             C:\Users\jonat\soccerdata\config\league_dict.json.

In [28]:
import warnings
from statsbombpy.api_client import NoAuthWarning

warnings.filterwarnings("ignore", category=NoAuthWarning)

In [29]:
fb = sd.FBref(leagues = "Big 5 European Leagues Combined", seasons = '15-16', no_cache = False, no_store = False)

[11/26/25 21:06:21] INFO     Saving cached data to C:\Users\jonat\soccerdata\data\FBref              ]8;id=572157;file://c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\soccerdata\_common.py\_common.py]8;;\:]8;id=613095;file://c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packages\soccerdata\_common.py#263\263]8;;\

In [30]:
# Loading Player Stats
# Step 1: load the standard stats for all Big 5 leagues
player_stats = fb.read_player_season_stats(stat_type="standard")

# Step 2: filter for Premier League only
player_stats = player_stats.loc["ENG-Premier League"]

# Take a look
player_stats.head()

[11/26/25 21:06:37] WARNING  c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packag ]8;id=229992;file://c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\warnings.py\warnings.py]8;;\:]8;id=454272;file://c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\warnings.py#109\109]8;;\
                             es\soccerdata\fbref.py:165: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(dfs)

                                       nation    pos age  born Playing Time  \
                                                                         MP
season team    player
1516   Arsenal Aaron Ramsey               WAL     MF  24  1990           31
               Alex Iwobi                 NGA  FW,MF  19  1996           13
               Alex Oxlade-Chamberlain    ENG  FW,MF  21  1993           22
               Alexis Sánchez             CHI  FW,MF  26  1988           30
               Calum Chambers             ENG  DF,MF  20  1995           12

                                                          Performance      \
                                       Starts   Min   90s         Gls Ast
season team    player
1516   Arsenal Aaron Ramsey                29  2623  29.1           5   4
               Alex Iwobi                   8   628   7.0           2   2
               Alex Oxlade-Chamberlain      9   926  10.3           1   0
               Alexis Sánchez              28  2436  27.1          13   4
               Calum Chambers               2   322   3.6           0   0

                                        ...                          \
                                        ... G-PK PK PKatt CrdY CrdR
season team    player                   ...
1516   Arsenal Aaron Ramsey             ...    5  0     0    4    0
               Alex Iwobi               ...    2  0     0    0    0
               Alex Oxlade-Chamberlain  ...    1  0     0    0    0
               Alexis Sánchez           ...   13  0     0    1    0
               Calum Chambers           ...    0  0     0    2    0

                                       Per 90 Minutes
                                                  Gls   Ast   G+A  G-PK G+A-PK
season team    player
1516   Arsenal Aaron Ramsey                      0.17  0.14  0.31  0.17   0.31
               Alex Iwobi                        0.29  0.29  0.57  0.29   0.57
               Alex Oxlade-Chamberlain            0.1   0.0   0.1   0.1    0.1
               Alexis Sánchez                    0.48  0.15  0.63  0.48   0.63
               Calum Chambers                     0.0   0.0   0.0   0.0    0.0

[5 rows x 21 columns]

In [31]:
def clean_player_stats_columns(player_stats: pd.DataFrame) -> pd.DataFrame:
    df = player_stats.copy()

    new_cols = []
    for col in df.columns:
        # MultiIndex entries: (top, sub)
        if isinstance(col, tuple):
            top, sub = col

            # nation, pos, age, born (where sub == '')
            if top == 'nation' and sub == '':
                new_cols.append('nation')
            elif top == 'pos' and sub == '':
                new_cols.append('pos')
            elif top == 'age' and sub == '':
                new_cols.append('age')
            elif top == 'born' and sub == '':
                new_cols.append('born')

            # Playing Time
            elif top == 'Playing Time' and sub == 'MP':
                new_cols.append('matches')
            elif top == 'Playing Time' and sub == 'Starts':
                new_cols.append('starts')
            elif top == 'Playing Time' and sub == 'Min':
                new_cols.append('minutes')
            elif top == 'Playing Time' and sub == '90s':
                new_cols.append('nineties')

            # Performance (counting stats)
            elif top == 'Performance' and sub == 'Gls':
                new_cols.append('goals')
            elif top == 'Performance' and sub == 'Ast':
                new_cols.append('assists')
            elif top == 'Performance' and sub == 'G+A':
                new_cols.append('g_plus_a')
            elif top == 'Performance' and sub == 'G-PK':
                new_cols.append('non_pen_goals')
            elif top == 'Performance' and sub == 'PK':
                new_cols.append('penalties_scored')
            elif top == 'Performance' and sub == 'PKatt':
                new_cols.append('penalties_attempted')
            elif top == 'Performance' and sub == 'CrdY':
                new_cols.append('yellow_cards')
            elif top == 'Performance' and sub == 'CrdR':
                new_cols.append('red_cards')

            # Per 90 Minutes
            elif top == 'Per 90 Minutes' and sub == 'Gls':
                new_cols.append('goals_p90')
            elif top == 'Per 90 Minutes' and sub == 'Ast':
                new_cols.append('assists_p90')
            elif top == 'Per 90 Minutes' and sub == 'G+A':
                new_cols.append('g_plus_a_p90')
            elif top == 'Per 90 Minutes' and sub == 'G-PK':
                new_cols.append('non_pen_goals_p90')
            elif top == 'Per 90 Minutes' and sub == 'G+A-PK':
                new_cols.append('g_plus_a_minus_pk_p90')

            # Fallback: if some unexpected (top, sub) shows up
            else:
                new_cols.append(f"{top}_{sub}".strip())

        # Scalar columns like 'season', 'team', 'player'
        else:
            new_cols.append(col)

    df.columns = new_cols

    df = df.reset_index()
    first_col = df.columns[0]
    df = df.drop(columns=[first_col])

    return df

In [32]:
player_stats = clean_player_stats_columns(player_stats)

In [33]:
player_stats = player_stats.reset_index()

In [34]:
player_stats.head()

,index,team,player,nation,pos,age,born,matches,starts,minutes,...,non_pen_goals,penalties_scored,penalties_attempted,yellow_cards,red_cards,goals_p90,assists_p90,g_plus_a_p90,non_pen_goals_p90,g_plus_a_minus_pk_p90
0,0,Arsenal,Aaron Ramsey,WAL,MF,24,1990,31,29,2623,...,5,0,0,4,0,0.17,0.14,0.31,0.17,0.31
1,1,Arsenal,Alex Iwobi,NGA,"FW,MF",19,1996,13,8,628,...,2,0,0,0,0,0.29,0.29,0.57,0.29,0.57
2,2,Arsenal,Alex Oxlade-Chamberlain,ENG,"FW,MF",21,1993,22,9,926,...,1,0,0,0,0,0.1,0.0,0.1,0.1,0.1
3,3,Arsenal,Alexis Sánchez,CHI,"FW,MF",26,1988,30,28,2436,...,13,0,0,1,0,0.48,0.15,0.63,0.48,0.63
4,4,Arsenal,Calum Chambers,ENG,"DF,MF",20,1995,12,2,322,...,0,0,0,2,0,0.0,0.0,0.0,0.0,0.0

In [35]:
#Loading Team Stats
team_stats = fb.read_team_season_stats(stat_type="standard")

team_stats = team_stats.loc["ENG-Premier League"]

team_stats.head()

[11/26/25 21:08:01] WARNING  c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\site-packag ]8;id=306997;file://c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\warnings.py\warnings.py]8;;\:]8;id=748502;file://c:\Users\jonat\AppData\Local\Programs\Python\Python311\Lib\warnings.py#109\109]8;;\
                             es\soccerdata\fbref.py:165: FutureWarning: The behavior of DataFrame
                             concatenation with empty or all-NA entries is deprecated. In a future
                             version, this will no longer exclude empty or all-NA columns when
                             determining the result dtypes. To retain the old behavior, exclude the
                             relevant entries before the concat operation.
                               pd.concat(dfs)

                      players_used   Age  Poss Playing Time                   \
                                                         MP Starts   Min 90s
season team
1516   Arsenal                  25  27.0  58.3           38    418  3420  38
       Aston Villa              29  26.6  46.4           38    418  3420  38
       Bournemouth              28  27.7  51.2           38    418  3420  38
       Chelsea                  28  26.8  56.2           38    418  3420  38
       Crystal Palace           30  27.7  45.8           38    418  3420  38

                      Performance           ...                     \
                              Gls Ast  G+A  ... PK PKatt CrdY CrdR
season team                                 ...
1516   Arsenal                 62  53  115  ...  1     2   45    0
       Aston Villa             24  19   43  ...  2     2   77    0
       Bournemouth             43  28   71  ...  3     4   53    0
       Chelsea                 55  40   95  ...  4     5   62    0
       Crystal Palace          38  21   59  ...  4     5   62    0

                      Per 90 Minutes                           \
                                 Gls   Ast   G+A  G-PK G+A-PK
season team
1516   Arsenal                  1.63  1.39  3.03  1.61    3.0
       Aston Villa              0.63   0.5  1.13  0.58   1.08
       Bournemouth              1.13  0.74  1.87  1.05   1.79
       Chelsea                  1.45  1.05   2.5  1.34   2.39
       Crystal Palace            1.0  0.55  1.55  0.89   1.45

                                                                     url

season team
1516   Arsenal               /en/squads/18bb7c10/2015-2016/Arsenal-Stats
       Aston Villa       /en/squads/8602292d/2015-2016/Aston-Villa-Stats
       Bournemouth       /en/squads/4ba7cbea/2015-2016/Bournemouth-Stats
       Chelsea               /en/squads/cff3d9bb/2015-2016/Chelsea-Stats
       Crystal Palace  /en/squads/47c64c55/2015-2016/Crystal-Palace-S...

[5 rows x 21 columns]

In [36]:
team_stats.columns

MultiIndex([(  'players_used',       ''),
            (           'Age',       ''),
            (          'Poss',       ''),
            (  'Playing Time',     'MP'),
            (  'Playing Time', 'Starts'),
            (  'Playing Time',    'Min'),
            (  'Playing Time',    '90s'),
            (   'Performance',    'Gls'),
            (   'Performance',    'Ast'),
            (   'Performance',    'G+A'),
            (   'Performance',   'G-PK'),
            (   'Performance',     'PK'),
            (   'Performance',  'PKatt'),
            (   'Performance',   'CrdY'),
            (   'Performance',   'CrdR'),
            ('Per 90 Minutes',    'Gls'),
            ('Per 90 Minutes',    'Ast'),
            ('Per 90 Minutes',    'G+A'),
            ('Per 90 Minutes',   'G-PK'),
            ('Per 90 Minutes', 'G+A-PK'),
            (           'url',       '')],
           )

In [37]:
def clean_team_stats(team_stats: pd.DataFrame) -> pd.DataFrame:
    df = team_stats.copy()

    # 1) Flatten / rename the MultiIndex columns
    new_cols = []
    for col in df.columns:
        if isinstance(col, tuple):
            top, sub = col

            # simple single-level ones
            if top == 'players_used' and sub == '':
                new_cols.append('players_used')
            elif top == 'Age' and sub == '':
                new_cols.append('avg_age')
            elif top == 'Poss' and sub == '':
                new_cols.append('possession')

            # Playing Time
            elif top == 'Playing Time' and sub == 'MP':
                new_cols.append('matches')
            elif top == 'Playing Time' and sub == 'Starts':
                new_cols.append('starts')
            elif top == 'Playing Time' and sub == 'Min':
                new_cols.append('minutes')
            elif top == 'Playing Time' and sub == '90s':
                new_cols.append('nineties')

            # Performance (totals)
            elif top == 'Performance' and sub == 'Gls':
                new_cols.append('goals')
            elif top == 'Performance' and sub == 'Ast':
                new_cols.append('assists')
            elif top == 'Performance' and sub == 'G+A':
                new_cols.append('g_plus_a')
            elif top == 'Performance' and sub == 'G-PK':
                new_cols.append('non_pen_goals')
            elif top == 'Performance' and sub == 'PK':
                new_cols.append('penalties_scored')
            elif top == 'Performance' and sub == 'PKatt':
                new_cols.append('penalties_attempted')
            elif top == 'Performance' and sub == 'CrdY':
                new_cols.append('yellow_cards')
            elif top == 'Performance' and sub == 'CrdR':
                new_cols.append('red_cards')

            # Per 90 Minutes
            elif top == 'Per 90 Minutes' and sub == 'Gls':
                new_cols.append('goals_p90')
            elif top == 'Per 90 Minutes' and sub == 'Ast':
                new_cols.append('assists_p90')
            elif top == 'Per 90 Minutes' and sub == 'G+A':
                new_cols.append('g_plus_a_p90')
            elif top == 'Per 90 Minutes' and sub == 'G-PK':
                new_cols.append('non_pen_goals_p90')
            elif top == 'Per 90 Minutes' and sub == 'G+A-PK':
                new_cols.append('g_plus_a_minus_pk_p90')

            # url
            elif top == 'url' and sub == '':
                new_cols.append('url')

            # fallback, in case something unexpected shows up
            else:
                new_cols.append(f"{top}_{sub}".strip())
        else:
            # scalar column name
            new_cols.append(col)

    df.columns = new_cols

    # 2) Reset index and split (season, team) if index is tuples
    df = df.reset_index()

    first_col = df.columns[0]
    if df[first_col].apply(lambda x: isinstance(x, tuple)).all():
        tup_len = len(df[first_col].iloc[0])

        if tup_len == 2:
            df[['season', 'team']] = pd.DataFrame(
                df[first_col].tolist(), index=df.index
            )
        elif tup_len == 3:
            df[['season', 'team', 'extra']] = pd.DataFrame(
                df[first_col].tolist(), index=df.index
            )

        df = df.drop(columns=[first_col])

    return df

In [38]:
team_stats = clean_team_stats(team_stats)

In [39]:
team_stats.head()

,season,team,players_used,avg_age,possession,matches,starts,minutes,nineties,goals,...,penalties_scored,penalties_attempted,yellow_cards,red_cards,goals_p90,assists_p90,g_plus_a_p90,non_pen_goals_p90,g_plus_a_minus_pk_p90,url
0,1516,Arsenal,25,27.0,58.3,38,418,3420,38,62,...,1,2,45,0,1.63,1.39,3.03,1.61,3.0,/en/squads/18bb7c10/2015-2016/Arsenal-Stats
1,1516,Aston Villa,29,26.6,46.4,38,418,3420,38,24,...,2,2,77,0,0.63,0.5,1.13,0.58,1.08,/en/squads/8602292d/2015-2016/Aston-Villa-Stats
2,1516,Bournemouth,28,27.7,51.2,38,418,3420,38,43,...,3,4,53,0,1.13,0.74,1.87,1.05,1.79,/en/squads/4ba7cbea/2015-2016/Bournemouth-Stats
3,1516,Chelsea,28,26.8,56.2,38,418,3420,38,55,...,4,5,62,0,1.45,1.05,2.5,1.34,2.39,/en/squads/cff3d9bb/2015-2016/Chelsea-Stats
4,1516,Crystal Palace,30,27.7,45.8,38,418,3420,38,38,...,4,5,62,0,1.0,0.55,1.55,0.89,1.45,/en/squads/47c64c55/2015-2016/Crystal-Palace-S...

In [40]:
def get_team_events(team_name, matches_df):
    # Identify matches where the team played
    match_ids = matches_df.query(
        "home_team == @team_name or away_team == @team_name"
    )["match_id"]

    all_events = []

    for mid in match_ids:
        df = sb.events(match_id=mid)

        # Keep only events performed BY this team,
        # during possessions belonging TO this team
        df = df[
            (df["possession_team"] == team_name) &
            (df["team"] == team_name)
        ]

        all_events.append(df)

    return pd.concat(all_events, ignore_index=True)

In [41]:
leicester_events = get_team_events("Leicester City", matches)

In [42]:
leicester_events.head()

,ball_receipt_outcome,ball_recovery_recovery_failure,carry_end_location,clearance_aerial_won,clearance_body_part,clearance_head,clearance_left_foot,clearance_right_foot,counterpress,dribble_nutmeg,...,pass_goal_assist,pass_straight,shot_deflected,goalkeeper_lost_out,goalkeeper_shot_saved_off_target,shot_saved_off_target,block_save_block,goalkeeper_shot_saved_to_post,goalkeeper_success_in_play,shot_saved_to_post
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN